// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pop_Simona_SADE.Data;

namespace Pop_Simona_SADE.Migrations
{
    [DbContext(typeof(ExhibitionContext))]
    [Migration("20220108121504_ExtendedModel")]
    partial class ExtendedModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pop_Simona_SADE.Models.Current", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CurrentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Particularity")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("ID");

                    b.ToTable("Current");
                });

            modelBuilder.Entity("Pop_Simona_SADE.Models.CurrentPainting", b =>
                {
                    b.Property<int>("PaintingID")
                        .HasColumnType("int");

                    b.Property<int>("CurrentID")
                        .HasColumnType("int");

                    b.HasKey("PaintingID", "CurrentID");

                    b.HasIndex("CurrentID");

                    b.ToTable("CurrentPainting");
                });

            modelBuilder.Entity("Pop_Simona_SADE.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Pop_Simona_SADE.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaintingID")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("PaintingID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Pop_Simona_SADE.Models.Painting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Painter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Painting");
                });

            modelBuilder.Entity("Pop_Simona_SADE.Models.CurrentPainting", b =>
                {
                    b.HasOne("Pop_Simona_SADE.Models.Current", "Current")
                        .WithMany("CurrentPaintings")
                        .HasForeignKey("CurrentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pop_Simona_SADE.Models.Painting", "Painting")
                        .WithMany("CurrentPaintings")
                        .HasForeignKey("PaintingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Current");

                    b.Navigation("Painting");
                });

            modelBuilder.Entity("Pop_Simona_SADE.Models.Order", b =>
                {
                    b.HasOne("Pop_Simona_SADE.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pop_Simona_SADE.Models.Painting", "Painting")
                        .WithMany("Orders")
                        .HasForeignKey("PaintingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Painting");
                });

            modelBuilder.Entity("Pop_Simona_SADE.Models.Current", b =>
                {
                    b.Navigation("CurrentPaintings");
                });

            modelBuilder.Entity("Pop_Simona_SADE.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Pop_Simona_SADE.Models.Painting", b =>
                {
                    b.Navigation("CurrentPaintings");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
